### ISSUE TITLE
clientside mixin on common side config

### ISSUE THREAD

**Issue by Linguardium** [Fabricators-of-Create/Registrate-Refabricated#4]
https://github.com/Fabricators-of-Create/Registrate-Refabricated/blob/e719b07f72b45e0a1abd42486fb9a817a589121d/src/main/resources/registrate-fabric.mixins.json#L8C31-L8C31

Not sure if this mod is intended to be clientside only, but the environment is marked * in fabric.mod.json causing it to be loaded on servers, and renderers are only clientside. The mixin should be moved in the config to the client mixin list

**Comment by IThundxr** [comment]
fixed in https://github.com/Fabricators-of-Create/Registrate-Refabricated/commit/7dad83dc7dc087f8acb2cb2ee84a12b6fa4dd715
